#!/bin/sh
HELM_BINARY=${HELM_BINARY:-/usr/local/bin/helm-binary}

## Enable --tls substitution for helm tls-enabled commands
#
__tls_commands="del delete get hist history install ls list reset rollback status test upgrade verify"
cmd="$1"
shift

args="$@"
enabled="yes y true enabled enable"

# enable tls
if ( echo "${__tls_commands}" | grep -wq "${cmd}" && echo "$enabled" | grep -wq "$HELM_FORCE_TLS" ); then
  args="--tls $@"
fi

$HELM_BINARY ${cmd} ${args}
